{{- range .Values.llama_factory.models }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .config.name }}
data:
  {{- with .config.cli_config}}
  llama4.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}