apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.llama_factory.config.name }}
data:
  {{- with .Values.llama_factory.config.cli_config}}
  llama4.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
