{{- if .Values.llama_factory.enabled }}
{{- $ctx := . }}
{{- range .Values.llama_factory.models }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  include "llama4-helm.fullname" $ctx }}
  labels:
    {{- include "llama4-helm.labels" $ctx | nindent 4 | default ( printf "app:" .model_name ) }}
spec:
  {{- if not $ctx.Values.autoscaling.enabled }}
  replicas: {{ $ctx.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llama4-helm.labels" $ctx | nindent 6 | default ( printf "app:" .model_name ) }}
  template:
    metadata:
      {{- with $ctx.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "llama4-helm.labels" $ctx | nindent 8 | default ( printf "app:" .model_name ) }}
        {{- with $ctx.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $ctx.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "llama4-helm.serviceAccountName" $ctx }}
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ $ctx.Chart.Name }}
        command: ["bash", "-c"]
        args:
          - | {{ include "llama_factory.renderBashCommand" . | default ( printf "llama-factory api " .templatepath ) }}

        {{- with .securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .image.repository | default "hiyouga/llamafactory:" }}:{{ .image.tag | default "latest" }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
          - name: openai
            containerPort: {{ .service.port }}
            protocol: TCP
      {{- if .healthcheck.enabled }}
        {{- with .healthcheck.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .healthcheck.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- end }}
      {{- if .env }}
        env:
        {{- range $key, $val := .env }}
          - name: {{ $key | upper | replace "-" "_" }}
            value: "{{ $val }}"
        {{- end }}
          - name: API_MODEL_NAME
            value: {{ .model_name | quote }}
      {{- end }}
        {{- with .resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: {{ .config.name }}
          mountPath: {{ .templatepath }}
          subPath: {{ .config.name }}
        - name: {{ $ctx.Values.storage.pvc.name }}
          mountPath: /workspace
        - name: dev-shm
          mountPath: /dev/shm
   {{- if $ctx.Values.storage.volumes }}
      volumes: 
      - name: {{ .config.name }}
        configMap:
          name: {{ .config.name }}
      - name: {{ $ctx.Values.storage.pvc.name }}
        persistentVolumeClaim:
          claimName: {{ $ctx.Values.storage.pvc.name }}-pvc
      - name: dev-shm
        emptyDir:
          medium: "Memory"
          sizeLimit: {{ $ctx.Values.storage.shmSize }}
    {{- end }}
      {{- with $ctx.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $ctx.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}