{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag | default "latest" }}"
          ports:
            - containerPort: {{ .port }}
          env:
            {{- toYaml .env | nindent 12 }}
---
{{- end }}