{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "apps require a unique name to create" .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag | default "latest" }}"
          {{- if .command }}
          command: {{ .command }}
          {{- end }}
          {{- if .extraArgs }}
          args: {{ .extraArgs }}
          {{- end }}
          ports:
            - containerPort: {{ .port }}
          env:
            {{- toYaml .env | nindent 12 }}
        {{- if .storage }}
          {{- if eq .storage.type "local" }}
          volumeMounts:
          - name: {{ .name }}
            mountPath: {{ .storage.path | default "/workspace"}}
      volumes:
      - name: {{ .name }}
        hostPath:
          path: {{ .storage.local_path | default "/home/ubuntu/agent-workspace" }}
          type: DirectoryOrCreate
          {{- else if eq .storage.type "pvc" -}}
          - name: {{ .storage.name | default "agent-volume" }}
          mountPath: /workspace
      volumes:
      - name: {{ .storage.name | default "agent-volume"}}
        persistentVolumeClaim:
          claimName: {{ .storage.name | default "agent" }}-pvc
          {{- end -}}
        {{- end -}}

        

{{- printf "\n---\n" }}
{{- end -}}