{{- $ctx := . }}
{{- range .Values.apps }}
{{- if and .storage ( ne .storage.type "local" ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .storage.name | default "agent"}}-pvc
spec:
  accessModes:
    - {{ .storage.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .storage.size | default "10Gi" }}
  storageClassName: {{ .storageClassName | quote | default "general" }}
{{- end }}
{{- end }}