# Default values for llama4-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# add vllm for some model that can't be deploy with llama-factory
apps:
  # - name: test
  #   image:
  #     repository: qdrant/qdrant
  #     tag: "latest"
  #   env:
  #     - name: API_URL
  #       value: "0.0.0.0:6443"
  #   services:
  #     - port: 6333
  #       name: qdrant-port
  #       type: ClusterIP
  #     - port: 6443
  #       name: qdrant-port-2
  #       type: ClusterIP
  #   replicaCount: 1
  #   storage:
  #     type: local
  #     path: "/qdrant/storage/collections"
  #     local_path: "/home/ubuntu/storage_qdrant"
  - name: Agent
    image:
      repository: kanic1111/agent-llm-api
      tag: "v1"
    command: ["uvicorn", "llm_api:app", "--host", "0.0.0.0", "--port", "7001"]
    # resources:
    #   limits:
    #     cpu: 800m
    #     memory: 128Mi
    # No Service – this pod is headless (e.g. a background worker)
    services:
    - port: 7001
      name: qdrant-port
      type: ClusterIP
    storage: 
      type: local
      size: 20Gi
      accessMode: ReadWriteMany
      storageClass: nfs-csi
    agent_config:
      # agent config
      # llm 基本 url、model_name
      # "http://140.110.160.97:30002/v1"
      # "ollama"
      # "llama4-scout"
      openai_base_url: "*.example.com"
      api_key: "0.0.0.0:6443"
      llm_model_name: "llama4-scout"
      # 預設 prompt 目前預設是 basic, 共有 basic , structured, article_qa, k8s_instruction 三總
      rompt_style: "k8s_instruction"
      # reranker 一次輸出數量
      reranker_top: 5
      # Qdrant name 機敏雲、可信賴雲
      SensiMesh_Qdrant_vector_collection_name: "SensiMesh_20250519_512_10_bge-m3"
      trusted_cloud_Qdrant_vector_collection_name: "trusted-cloud_20250701_512_10_bge-m3"

      # embed_model name 
      embed_model_name: "bge-m3"

      # 預設溫度參數
      temperature: 0.0

      # image IP 設定，用來處理圖片抓取用的
      server:
        host_ip: "140.110.160.24"
        port: 8005
        image_base_url: "http://140.110.160.10:8005/images"
      

qdrant:
  name: qdrant
  image:
    repository: qdrant/qdrant
    tag: "latest"
  env:
    - name: API_URL
      value: "0.0.0.0:6443"
  services:
    - port: 6333
      name: qdrant-port
      type: ClusterIP
    - port: 6443
      name: qdrant-port-2
      type: ClusterIP
  replicaCount: 1
  storage:
    type: local
    path: "/qdrant/storage/collections"
    local_path: "/home/ubuntu/storage_qdrant"

ollama:
  name: test
  replicas: 1
  image:
    repository: ollama/ollama
    tag: "latest"
  env:
    - name: OLLAMA_HOST
      value: "0.0.0.0:11434"
  services:
    - name: ollama-nodeport
      port: 11434
      targetport: 11434
      nodeport: 30100
      type: NodePort
    - name: ollama-port
      port: 11434
      targetport: 11434
      type: ClusterIP

models:
- infer_method: "llama-factory"
  image:
    repository: kanic1111/llama-factory
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "05-23"
  model_name: RedHatAI/Llama-4-Scout-17B-16E-Instruct-FP8-dynamic
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000
  # hf_cache: true 
  # env for both llama-factory and hugging face
  # env are all optional but the cache store should be point to the pvc mount path
  env:
    huggingface-cache: true
    hf-home: "/workspace/hf/cache"
    huggingface-hub-cache: "/workspace/hf/hub_cache"
    api-port: "8000"
    vllm-allow-long-max-model-len: "0"
    hf_token: ""
  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: NodePort
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 8000 #LLM Listened Posrt
    nodeport: 30003 # nodeport for LLM Service
      #config path to Llama-factory

  # for CLI arg please check llamafactory github: https://github.com/hiyouga/LLaMA-Factory/tree/main 
  # vllm max_model_len adjust by yourself
  # cli_args:
  #   infer_backend: vllm #llama-factory supports huggingface sglangs vllm
  #   mode: api # check llamafactory github to see all avaliable options
  #   vllm:
  #     extraArgs:
  #       vllm_enforce_eager: true
  #       vllm_gpu_util: 0.9
  #       vllm_maxlen: 32768
  cli_args:
    infer_backend: vllm #llama-factory supports huggingface sglangs vllm
    mode: api # check llamafactory github to see all avaliable options
    vllm:
      extraArgs:
        vllm_enforce_eager: true
        vllm_gpu_util: 0.9
        vllm_maxlen: 32768

  # for template please check llamafactory github: https://github.com/hiyouga/LLaMA-Factory/tree/main
  # examples for inference :
  # config:
  #   name: llama4-config-2
  #   filename: llama4.yaml
  #   template:
  #     model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
  #     template: llama3
  #     infer_backend: huggingface  # choices: [huggingface, vllm, sglang]
  #     trust_remote_code: true

  templatepath: "/workspace/config/llama4.yaml"
  config:
    name: llama4-config-2
    filename: llama4.yaml
    template:
      model_name_or_path: RedHatAI/Llama-4-Scout-17B-16E-Instruct-FP8-dynamic
      template: llama4
      infer_backend: vllm
      trust_remote_code: true
  healthcheck:
    enabled: false
    livenessProbe:
      httpGet:
        path: /v1/models
        port: 8000
    readinessProbe:
      httpGet:
        path: /v1/models
        port: 8000
  resources:
    limits:
      nvidia.com/gpu: 1 #llama4 require at leastt 150GB memory  
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #  cpu: 100m
    #   memory: 128Mi
  # env example:
  # env:
  #   huggingface-cache: true
  #   hf-home: "/workspace/huggingface/cache"
  #   
  # This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/

  #pvc example
  pvc:
    enabled: true
    use_existed: false
    name: workspace
    storageClassName: "nfs-csi"
    accessMode: ReadWriteMany
    size: 1Ti # atleast 500GB needed to download model

- infer_method: vllm
  name: "vllm-container"
  model_name: "RedHatAI/whisper-large-v3-FP8-Dynamic"
  replicaCount: 1
  hf_token: ""
  image:
    repository: vllm/vllm-openai
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "gptoss"
  extraArgs:
    --enforce-eager: true
    --gpu-memory-utilization: 0.7
    --max-model-len: 448  
    --async-scheduling: true
  pvc:
    enabled: true
    use_existed: true
    name: workspace
    storageClassName: "nfs-csi"
    accessMode: ReadWriteMany
    size: 1Ti 
  env:
    huggingface-cache: true
    hf-home: "/workspace/hf/cache"
    huggingface-hub-cache: "/workspace/hf/hub_cache"
    api-port: "8000"
    vllm-allow-long-max-model-len: "0"
    hf_token: ""
  config:
    name: deepspeed_config
    path: config/deepspeed_config.json
    
    
  # This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
  service:
    # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
    type: NodePort
    name: vllm-port # leave it empty will have random ganerated name 
    # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
    port: 8000 #LLM Listened Posrt
    nodeport: 30003
  healthcheck:
    enabled: false
    livenessProbe:
      httpGet:
        path: /v1/models
        port: 8000
    readinessProbe:
      httpGet:
        path: /v1/models
        port: 8000
  resources:
    limits:
      nvidia.com/gpu: 1 

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""


# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000




# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false # true if you want ingress
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: llama4-fp8.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
# autoscaling doesn't work on inference
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


# Additional volumes on the output Deployment definition.
storage:
  shmSize: 64Gi
  volumes: 
  - name: "{{ .Values.llama_factory.config.name }}"
    configMap:
      name: "{{ .Values.llama_factory.config.name }}"
  - name: "{{ .Values.storage.pvc.name }}"
    persistentVolumeClaim:
      claimName: "{{ .Values.storage.pvc.name }}-pvc"
  - name: dev-shm
    emptyDir:
      medium: "Memory"
      sizeLimit: "{{ .Values.storage.shmSize }}"

  # volume example
  # - name: workspace
  # persistentVolumeClaim:
  #   claimName: "{{ .Values.storage.pvc.name }}-pvc"
  local-storage:
    enabled: false #does not recommand to use local mountpoint
    path: /mnt/model_save # any location that have 500Gb or above

  #pvc example

  pvc:
    enabled: true
    use_existed: false
    name: workspace
    storageClassName: "nfs-csi"
    accessMode: ReadWriteMany
    size: 1Ti # atleast 500GB needed to download model

# Additional volumeMounts on the output Deployment definition.
volumeMounts: 
- name: "{{ .Values.llama_factory.config.name }}"
  mountPath: "{{ .Values.llama_factory.templatepath }}"
  subPath: "{{ .Values.llama_factory.config.name }}"
- name: "{{ .Values.storage.pvc.name }}"
  mountPath: /workspace
- name: dev-shm
  mountPath: /dev/shm

nodeSelector: {}

tolerations: []

affinity: {}
